# site settings
title: Life Builders Community Church
title_trust: Life Builders Community Trust, Kolkata
subtitle: Kolkata
email: youremailaddress@gmail.com
description: A warm and Christ-centered community for all
baseurl: "/lbcc-site" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: New Town Action Area 3
city: Kolkata
state: West Bengal
zip_code: 700 160
country: India
phone: +91 8420242594 / +91 9748804704
design_by: Rimil Solutions
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/LBCCKolkata/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
