# site settings
title: Life Builders Community Church
title_trust: Life Builders Community Trust, Kolkata
subtitle: Kolkata
email: youremailaddress@gmail.com
description: A warm and Christ-centered community for all
baseurl: "/lbcc-site" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: New Town Action Area 3
city: Kolkata
state: West Bengal
zip_code: 700 160
country: India
phone: +91 8420242594
design_by: Rimil Solutions
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
